### ISSUE TITLE
Change background character based on victory

### ISSUE THREAD

**Issue by AndBM** [AndBM/helichrysum#5]
It would be cool that instead of the Chancellor being the background character, it was the color of the previous winner, i.e. if Red won last game, the Red character was in the background.

The images exist in assets, and the information should be in the save object in the scripts. Probably we should assign each character a CSS class and write a script like

    document.getElementById("BG").className = "RedCharacter";

I will look into it later.

**Comment by alexrutar** [comment]
I think you can just modify the background image directly: something like
```
document.body.style.backgroundImage = "transparent url(../images/Oath-Character-Art-Chancellor-optim.png)";
```
or whatever the image file name is.

**Comment by alexrutar** [comment]
This should be done. Preview at [dynamic-bg-image.helichrysum.pages.dev](https://dynamic-bg-image.helichrysum.pages.dev)

**Comment by alexrutar** [comment]
I also rebased on top of the `code-cleanup` branch since I had made some changes to the javascript files, and also did some renaming there too, so this will fix some issues in the future.
