### ISSUE TITLE
Find and prepare citizen character art

### ISSUE THREAD

**Issue by AndBM** [AndBM/helichrysum#7]
All character art seems to be available in [this thread](https://boardgamegeek.com/thread/2305701/hyping-about-new-meeples-and-art). I am in the process of cutting out the citizen art and converting it to cutouts with transparent backgrounds. Paint 3D is surprisingly useful for this!

**Comment by AndBM** [comment]
The resolution of the citizen art is too low - either find a better picture or decrease the size.

**Comment by alexrutar** [comment]
New assets are now in `assets/character_art/combo_*.jpeg`

**Comment by alexrutar** [comment]
I did some crude cropping attempts, which were OK, but they decreased boundary clarity a bit too much in my opinion.

**Comment by AndBM** [comment]
I kind of like it. Closing for now.
