### ISSUE TITLE
Automate Dramatis Personæ table

### ISSUE THREAD

**Issue by AndBM** [AndBM/helichrysum#8]
The contents of the Dramatis Personæ table can be automated from the savestring. Assign each color a player name and collect the information on who won to make them chancellor, and list the other players with proper portraits and exile status.

Perhaps we can also add citizen portraits from the citizen character art.

**Comment by alexrutar** [comment]
This will be a good chance to move a lot of the `index.md` code directly into `_layouts/default.html`. It would be reasonable to render the entire "Game State" section all in one go. Then the "Helichrysum Chronicle" section can remain in the `index.md` page to make it easy to write in the new stories.

Maybe reasonable to put this in `_includes` and then import, for organizational clarity?

**Comment by AndBM** [comment]
Sounds like a great idea!
